export const TOPICS = {
  "world war ii": {
    topic: "World War II",
    intro: "World War II stands as the deadliest conflict in human history, claiming over 70 million lives and reshaping the global order in ways that still echo today. Born from the ashes of World War I's unresolved grievances and the rise of totalitarian regimes in Germany, Italy, and Japan, the war pitted the Allied powers against the Axis in a struggle that tested humanity's capacity for both destruction and resilience. From the beaches of Normandy to the Pacific islands, this global conflagration forged the modern world through unimaginable sacrifice and technological innovation.",
    outro: {
      summary: "World War II's legacy endures in the United Nations, NATO, and the European Union, institutions born from the ashes of conflict to prevent future wars. The war accelerated technological advancements from jet engines to nuclear power, fundamentally changing how we live and fight. Surprisingly, the conflict also led to the discovery that penguins in Antarctica had never seen humans before, as their remote habitat remained untouched throughout the war.",
      question: "How might the world be different if the atomic bomb had never been developed..."
    },
    related: ["world war i", "cold war", "nelson mandela"],
    events: [
      { date: "Sep 1939", title: "Germany invades Poland", summary: "Hitler's blitzkrieg triggers declarations of war from Britain and France.", detail: "On September 1, 1939, Nazi Germany launched a full-scale invasion of Poland. Two days later, Britain and France declared war on Germany, formally beginning the Second World War.", type: "war" },
      { date: "Jun 1940", title: "Fall of France", summary: "Nazi Germany defeats France in just six weeks, shocking the world.", detail: "The Wehrmacht swept through Belgium and northern France, outflanking the Maginot Line. France signed an armistice on June 22, leaving Britain as the last major Allied power in Western Europe.", type: "war" },
      { date: "Jul 1940", title: "Battle of Britain begins", summary: "RAF fights off the Luftwaffe in history's first major air battle.", detail: "Germany launched a sustained aerial bombing campaign to gain air supremacy before invading Britain. The Royal Air Force, aided by radar, successfully repelled the Luftwaffe — Hitler's first major defeat.", type: "war" },
      { date: "Jun 1941", title: "Operation Barbarossa", summary: "Germany launches the largest military invasion in history against the USSR.", detail: "With 3 million troops, Germany invaded the Soviet Union along a 2,900 km front. Initial advances were massive, but Soviet resistance stiffened by winter, opening an Eastern Front that would consume the bulk of German power.", type: "war" },
      { date: "Dec 1941", title: "Japan attacks Pearl Harbor", summary: "US enters the war after Japan's surprise attack on its Pacific fleet.", detail: "Japanese aircraft launched a surprise attack on Pearl Harbor on December 7, killing 2,400 Americans. The US declared war the next day, making the conflict truly global.", type: "political" },
      { date: "1942–43", title: "Battle of Stalingrad", summary: "Soviet forces encircle a German army in the war's pivotal turning point.", detail: "The months-long battle for Stalingrad was the bloodiest in history. Germany's Sixth Army was encircled and forced to surrender in February 1943, marking the beginning of Germany's long retreat.", type: "war" },
      { date: "Jun 1944", title: "D-Day — Normandy landings", summary: "Allied forces land in France, opening the Western Front.", detail: "Over 156,000 Allied troops landed on five beaches in Normandy on June 6, 1944 — the largest seaborne invasion in history — beginning the liberation of Western Europe.", type: "war" },
      { date: "May 1945", title: "Germany surrenders — V-E Day", summary: "Hitler dies by suicide; Germany signs unconditional surrender.", detail: "Soviet forces captured Berlin in late April 1945. Hitler died by suicide on April 30. Germany signed an unconditional surrender on May 8, ending the war in Europe.", type: "political" },
      { date: "Aug 1945", title: "Atomic bombs end the Pacific war", summary: "US drops nuclear bombs on Hiroshima and Nagasaki; Japan surrenders.", detail: "The US dropped atomic bombs on Hiroshima and Nagasaki on August 6 and 9, killing up to 210,000 people. Japan announced its surrender on August 15, formally ending the deadliest war in human history.", type: "war" },
      { date: "Oct 1945", title: "United Nations founded", summary: "World powers establish the UN to prevent future global conflicts.", detail: "The United Nations was officially established on October 24, 1945, with 51 founding member states, created to maintain international peace and foster cooperation between nations.", type: "political" },
    ]
  },
  "cold war": {
    topic: "The Cold War",
    intro: "The Cold War defined the second half of the 20th century as a tense standoff between the United States and the Soviet Union, neither side willing to engage in direct combat but both determined to expand their influence across the globe. This ideological battle between capitalism and communism played out through proxy wars, espionage, and an arms race that brought humanity to the brink of nuclear annihilation. From the Berlin Airlift to the Cuban Missile Crisis, the Cold War shaped international relations, technological innovation, and cultural divisions that persist in subtle ways today.",
    outro: {
      summary: "The Cold War's end in 1991 ushered in a unipolar world dominated by the United States, but it also left a legacy of nuclear proliferation and ideological divides that continue to influence global politics. The space race, born from Cold War competition, gave us satellites, GPS, and the moon landing, transforming communication and exploration. Surprisingly, the conflict also indirectly led to the creation of the internet, as ARPANET was developed by the US Department of Defense to maintain communication in case of nuclear attack.",
      question: "What would modern geopolitics look like if the Soviet Union had won the Cold War..."
    },
    related: ["world war ii", "space race", "elon musk"],
    events: [
      { date: "1947", title: "Truman Doctrine announced", summary: "US commits to containing Soviet communism globally.", detail: "President Truman asked Congress for aid to Greece and Turkey, establishing the doctrine that the US would support free peoples resisting communist subjugation — the formal start of containment strategy.", type: "political" },
      { date: "1948–49", title: "Berlin Blockade & Airlift", summary: "Soviets blockade West Berlin; Western powers respond with a massive airlift.", detail: "The Soviet Union blockaded road and rail access to West Berlin. Western allies responded with an 11-month airlift supplying the city. The Soviets lifted the blockade — a major early Western victory.", type: "political" },
      { date: "1949", title: "NATO founded & USSR tests atom bomb", summary: "The Western military alliance forms as Soviets end US nuclear monopoly.", detail: "NATO was founded in April 1949 as a collective defense alliance. Months later, the Soviet Union successfully tested its first atomic bomb, accelerating the arms race that would define the Cold War.", type: "political" },
      { date: "1950–53", title: "Korean War", summary: "First hot proxy war of the Cold War ends in stalemate at the 38th parallel.", detail: "North Korea invaded South Korea in 1950. A US-led UN coalition intervened. The war ended in an armistice in 1953 with the peninsula still divided — a preview of future Cold War proxy conflicts.", type: "war" },
      { date: "1957", title: "Sputnik launches the Space Race", summary: "USSR shocks the world with the first artificial satellite.", detail: "The Soviet Union launched Sputnik 1 on October 4, 1957. The achievement terrified the US, triggering massive investment in science, education, and space technology.", type: "science" },
      { date: "1962", title: "Cuban Missile Crisis", summary: "Thirteen days brought the world to the brink of nuclear war.", detail: "US reconnaissance discovered Soviet missiles in Cuba. For 13 days, the US and USSR faced off in the Cold War's most dangerous moment. A secret deal resolved the crisis — US removes missiles from Turkey, USSR removes from Cuba.", type: "political" },
      { date: "1969", title: "US lands on the Moon", summary: "Apollo 11 wins the Space Race for the United States.", detail: "Neil Armstrong and Buzz Aldrin became the first humans to walk on the Moon on July 20, 1969. The achievement was the defining victory for the US in the Cold War's most visible arena.", type: "science" },
      { date: "1979–89", title: "Soviet–Afghan War", summary: "A decade-long quagmire bleeds the Soviet Union dry.", detail: "The Soviet Union invaded Afghanistan in 1979. The US covertly armed the Afghan mujahideen. The war cost the Soviets over 15,000 lives and enormous resources — a key factor in the USSR's eventual collapse.", type: "war" },
      { date: "Nov 1989", title: "Berlin Wall falls", summary: "The Iron Curtain's most powerful symbol comes down.", detail: "On November 9, 1989, East Germany opened its borders and crowds began tearing down the Berlin Wall — symbolizing the collapse of communist regimes across Eastern Europe.", type: "political" },
      { date: "Dec 1991", title: "Soviet Union dissolves", summary: "The USSR officially breaks apart, ending the Cold War.", detail: "Gorbachev resigned on December 25, 1991 and the Soviet Union formally dissolved into 15 independent states, leaving the United States as the world's sole superpower.", type: "political" },
    ]
  },
  "bitcoin": {
    topic: "Bitcoin",
    intro: "Bitcoin emerged in 2008 as a radical response to the global financial crisis, offering a decentralized alternative to traditional banking systems controlled by governments and corporations. Created by the pseudonymous Satoshi Nakamoto, this digital currency promised to democratize money by removing intermediaries and enabling peer-to-peer transactions secured by cryptography. As the first cryptocurrency, Bitcoin challenged fundamental assumptions about value, trust, and monetary policy, sparking a revolution that has grown from a niche experiment to a global phenomenon worth trillions.",
    outro: {
      summary: "Bitcoin's success has inspired thousands of alternative cryptocurrencies and blockchain applications, from smart contracts to decentralized finance, fundamentally changing how we think about digital assets. The cryptocurrency has become a store of value for millions, with institutional adoption growing rapidly despite regulatory uncertainty. Surprisingly, Bitcoin mining consumes more electricity annually than some entire countries, raising questions about its environmental impact despite its carbon-neutral design.",
      question: "How would traditional banking systems need to evolve to compete with decentralized cryptocurrencies..."
    },
    related: ["amazon", "apple", "internet history"],
    events: [
      { date: "Oct 2008", title: "Bitcoin whitepaper published", summary: "Satoshi Nakamoto releases the foundational paper for Bitcoin.", detail: "On October 31, 2008, the anonymous Satoshi Nakamoto published 'Bitcoin: A Peer-to-Peer Electronic Cash System' — describing a decentralized digital currency using blockchain, released during the global financial crisis.", type: "science" },
      { date: "Jan 2009", title: "Bitcoin genesis block mined", summary: "The Bitcoin network launches with the first block ever mined.", detail: "Satoshi Nakamoto mined Block 0 on January 3, 2009, embedding the headline 'Chancellor on brink of second bailout for banks.' This launched the Bitcoin network and contained the first 50 BTC reward.", type: "science" },
      { date: "May 2010", title: "Bitcoin Pizza Day", summary: "10,000 BTC spent on two pizzas — the first real-world transaction.", detail: "Laszlo Hanyecz paid 10,000 BTC for two Papa John's pizzas — the first documented commercial Bitcoin transaction. At peak prices, those pizzas would be worth over $600 million.", type: "economy" },
      { date: "2013", title: "First major bull run to $1,000", summary: "Bitcoin surges past $1,000 for the first time.", detail: "In November 2013, Bitcoin crossed $1,000 driven by growing attention and the Cyprus banking crisis. The price crashed soon after, beginning a bear market that lasted nearly two years.", type: "economy" },
      { date: "2017", title: "Bitcoin hits $20,000", summary: "Crypto mania pushes Bitcoin to its first all-time high.", detail: "In December 2017, Bitcoin surged to nearly $20,000 driven by retail investor frenzy and ICO speculation. The crash that followed wiped out 80% of its value over the next year.", type: "economy" },
      { date: "2020", title: "Institutional adoption begins", summary: "MicroStrategy, Square, and Tesla buy Bitcoin as treasury assets.", detail: "Major corporations began holding Bitcoin on their balance sheets in 2020. MicroStrategy led the charge, followed by Square and Tesla, lending Bitcoin newfound institutional legitimacy.", type: "economy" },
      { date: "Nov 2021", title: "Bitcoin peaks at $69,000", summary: "Bitcoin reaches its highest-ever price during a historic bull market.", detail: "Bitcoin hit an all-time high of approximately $69,000 on November 10, 2021, driven by institutional demand and the launch of Bitcoin ETFs in Canada. A prolonged bear market followed through 2022.", type: "economy" },
      { date: "Jan 2024", title: "US Spot Bitcoin ETF approved", summary: "The SEC approves the first US spot Bitcoin ETFs — a landmark moment.", detail: "The SEC approved 11 spot Bitcoin ETFs on January 10, 2024. Products from BlackRock and Fidelity launched the same day, making Bitcoin accessible to millions of traditional investors for the first time.", type: "political" },
      { date: "Apr 2024", title: "Fourth Bitcoin halving", summary: "Bitcoin's block reward halves to 3.125 BTC.", detail: "The fourth Bitcoin halving reduced the mining reward from 6.25 to 3.125 BTC. Halvings occur every ~4 years and reduce Bitcoin's supply issuance rate, historically preceding major bull markets.", type: "economy" },
    ]
  },
  "iphone": {
    topic: "The iPhone",
    intro: "The iPhone revolutionized personal technology when it launched in 2007, transforming a simple communication device into a pocket-sized computer that redefined how we live, work, and connect. Steve Jobs' vision of a device that combined phone, internet, and media player created the smartphone category and disrupted industries from music to navigation. With its intuitive touch interface and App Store ecosystem, the iPhone didn't just change phones—it changed everything about modern life.",
    outro: {
      summary: "The iPhone's App Store has generated over $200 billion for developers and created entirely new industries, from ride-sharing to food delivery. Its design language influenced countless products and established Apple as the world's most valuable company. Surprisingly, the iPhone's camera has been used to document more historical events and personal moments than any other device in history, from Arab Spring protests to everyday family memories.",
      question: "What aspects of daily life would be fundamentally different without smartphones..."
    },
    related: ["apple", "elon musk", "ai history"],
    events: [
      { date: "Jan 2007", title: "Steve Jobs unveils the iPhone", summary: "Jobs introduces a touchscreen phone that will change the world.", detail: "On January 9, 2007, Steve Jobs announced the first iPhone at Macworld, calling it 'a revolutionary mobile phone, a widescreen iPod, and an internet communicator.' The audience reaction was electric.", type: "culture" },
      { date: "Jun 2007", title: "iPhone goes on sale for $499", summary: "Queues around the block as the first iPhone launches.", detail: "The original iPhone launched on June 29, 2007. Despite its high price and lack of 3G, it sold 1.4 million units in its first 90 days, stunning the mobile industry.", type: "economy" },
      { date: "Jul 2008", title: "App Store launches", summary: "Apple opens the App Store with 500 apps, creating a new economy.", detail: "The App Store launched on July 10, 2008. It fundamentally changed software distribution, enabling independent developers to reach millions of users. Today it generates over $85 billion annually.", type: "economy" },
      { date: "Jun 2010", title: "iPhone 4 and Retina display", summary: "A stunning new display and FaceTime redefine the smartphone.", detail: "The iPhone 4 introduced the Retina display with unprecedented pixel density and FaceTime video calling. Its iconic glass-and-steel design was widely imitated despite the 'antennagate' controversy.", type: "science" },
      { date: "Oct 2011", title: "Siri launches on iPhone 4S", summary: "Apple debuts the first mainstream AI voice assistant.", detail: "The iPhone 4S introduced Siri, a conversational voice assistant. Though initially limited, Siri planted the seeds for the AI assistant revolution and made voice computing mainstream.", type: "science" },
      { date: "Sep 2017", title: "iPhone X — the all-screen era", summary: "Face ID and an edge-to-edge OLED display reshape the smartphone.", detail: "Released for iPhone's 10th anniversary, the iPhone X removed the home button, introduced Face ID, and featured an edge-to-edge OLED display. Its design language defined smartphones for years.", type: "science" },
      { date: "2020", title: "iPhone 12 — 5G arrives", summary: "Apple brings 5G connectivity to its entire iPhone lineup.", detail: "The iPhone 12 lineup introduced 5G across all models and returned to a flat-edged design reminiscent of the iPhone 4. It became one of Apple's best-selling iPhone generations.", type: "science" },
      { date: "Sep 2023", title: "iPhone 15 adopts USB-C", summary: "Apple ditches Lightning for USB-C under EU regulatory pressure.", detail: "The iPhone 15 replaced Lightning with USB-C after the EU mandated a common charger standard. The Pro models introduced a titanium frame and 48MP main camera.", type: "science" },
    ]
  },
  "french revolution": {
    topic: "French Revolution",
    intro: "The French Revolution of 1789 stands as one of history's most transformative upheavals, overthrowing absolute monarchy and aristocratic privilege to establish the principles of liberty, equality, and fraternity that still shape modern democracy. Sparked by financial crisis, food shortages, and Enlightenment ideas, the revolution began with the storming of the Bastille and evolved through phases of radical change, terror, and eventual stabilization under Napoleon. This tumultuous period not only reshaped France but also inspired revolutionary movements worldwide and challenged the very foundations of social order.",
    outro: {
      summary: "The French Revolution's ideals of liberty, equality, and fraternity became foundational principles for modern democracies, influencing constitutions from the United States to many European nations. The revolution accelerated the spread of metric measurements, secular education, and modern administrative systems across Europe. Surprisingly, the conflict also led to the widespread adoption of the guillotine as a supposedly humane execution method, which ironically became a symbol of the revolution's violent excesses.",
      question: "How would European history have unfolded if the French monarchy had successfully reformed rather than being overthrown..."
    },
    related: ["world war i", "world war ii", "india independence"],
    events: [
      { date: "May 1789", title: "Estates-General convenes", summary: "France's first national assembly in 175 years sparks political crisis.", detail: "King Louis XVI convened the Estates-General to address France's financial crisis. Disputes over voting procedures quickly escalated into a political crisis that would topple the monarchy.", type: "political" },
      { date: "Jun 1789", title: "Tennis Court Oath", summary: "Third Estate vows not to dissolve until France has a constitution.", detail: "Locked out of their meeting hall, representatives of the Third Estate gathered at a nearby tennis court and swore not to dissolve until they had given France a constitution — defying royal authority.", type: "political" },
      { date: "Jul 14, 1789", title: "Storming of the Bastille", summary: "Parisian mob storms the royal fortress — the revolution's defining moment.", detail: "Thousands of Parisians stormed the Bastille fortress, freeing prisoners and seizing weapons. The event became the revolution's defining symbol, and July 14 is still France's national holiday.", type: "war" },
      { date: "Aug 1789", title: "Declaration of the Rights of Man", summary: "France proclaims liberty, equality, and popular sovereignty.", detail: "The National Assembly adopted the Declaration of the Rights of Man and Citizen, proclaiming that sovereignty rests in the nation. Inspired by Enlightenment philosophy, it remains a foundational document of liberal democracy.", type: "political" },
      { date: "1791", title: "Constitutional monarchy established", summary: "France becomes a constitutional monarchy, limiting royal power.", detail: "France adopted its first constitution in 1791, establishing a constitutional monarchy. Louis XVI was reduced to a figurehead — a compromise that satisfied neither republicans nor royalists.", type: "political" },
      { date: "Sep 1792", title: "First French Republic declared", summary: "The monarchy is abolished and France becomes a republic.", detail: "Following evidence of Louis XVI's dealings with foreign enemies, the monarchy was abolished on September 21, 1792. France became a republic, setting the stage for the king's trial.", type: "political" },
      { date: "Jan 1793", title: "Louis XVI executed", summary: "The king is guillotined before a crowd of thousands in Paris.", detail: "Louis XVI was tried for treason and guillotined on January 21, 1793. His execution shocked European monarchies and triggered a coalition of nations against France.", type: "political" },
      { date: "1793–94", title: "The Reign of Terror", summary: "Radical Jacobins execute thousands in the name of revolutionary purity.", detail: "Under Robespierre, approximately 17,000 people were officially executed and 10,000 died in prison. The Terror ended when Robespierre himself was guillotined in July 1794.", type: "war" },
      { date: "Nov 1799", title: "Napoleon seizes power", summary: "Napoleon Bonaparte's coup ends the revolutionary period.", detail: "On November 9, 1799, Napoleon staged a coup and established the Consulate with himself as First Consul. The revolution had consumed itself and given birth to military dictatorship.", type: "political" },
    ]
  },
  "space race": {
    topic: "The Space Race",
    intro: "The Space Race captured humanity's imagination as the United States and Soviet Union competed to conquer the final frontier, transforming scientific ambition into a Cold War battle for technological supremacy. From Sputnik's beep to Apollo 11's moon landing, this competition accelerated aerospace innovation at unprecedented speed, pushing the boundaries of human capability and expanding our understanding of the universe. The race didn't just put men on the moon—it created the modern space industry and inspired generations to dream of exploring beyond Earth.",
    outro: {
      summary: "The Space Race's legacy includes GPS navigation, satellite television, weather forecasting, and countless technological spinoffs that benefit daily life. It established the International Space Station and paved the way for commercial spaceflight companies like SpaceX. Surprisingly, the competition also led to the development of Tang orange drink as a way to provide astronauts with vitamin C, which became a popular consumer product despite its original purpose.",
      question: "What new frontiers might humanity explore if the Space Race had never happened..."
    },
    related: ["cold war", "elon musk", "ai history"],
    events: [
      { date: "Oct 1957", title: "Sputnik 1 launches", summary: "USSR shocks the world with the first artificial satellite.", detail: "The Soviet Union launched Sputnik 1 on October 4, 1957. Its radio beeps were heard worldwide, causing panic in the US and triggering the Space Race.", type: "science" },
      { date: "Apr 1961", title: "Yuri Gagarin orbits Earth", summary: "Soviet cosmonaut becomes the first human in space.", detail: "Yuri Gagarin orbited Earth once aboard Vostok 1 in 108 minutes on April 12, 1961 — a massive Soviet triumph that prompted Kennedy's bold Moon pledge.", type: "science" },
      { date: "May 1961", title: "Kennedy pledges Moon landing", summary: "JFK commits the US to landing on the Moon before 1970.", detail: "Weeks after Gagarin's flight, Kennedy addressed Congress: 'I believe this nation should commit itself to landing a man on the Moon before this decade is out.' It galvanized the entire US space program.", type: "political" },
      { date: "Feb 1962", title: "John Glenn orbits Earth", summary: "First American to orbit Earth aboard Friendship 7.", detail: "John Glenn completed three orbits in under five hours on February 20, 1962, restoring American confidence and turning Glenn into a national hero.", type: "science" },
      { date: "Mar 1965", title: "First spacewalk by Alexei Leonov", summary: "Soviet cosmonaut floats freely in space for 12 minutes.", detail: "Alexei Leonov left his Voskhod 2 capsule on March 18, 1965 for the first extravehicular activity in history. His suit inflated dangerously, nearly preventing his return.", type: "science" },
      { date: "Jan 1967", title: "Apollo 1 fire kills three astronauts", summary: "A launchpad fire during training devastates NASA.", detail: "A cabin fire killed Gus Grissom, Ed White, and Roger Chaffee on January 27, 1967. The tragedy forced a major capsule redesign and an 18-month halt to crewed flights.", type: "war" },
      { date: "Dec 1968", title: "Apollo 8 orbits the Moon", summary: "Humans see the far side of the Moon for the first time.", detail: "Apollo 8 made humans the first to orbit the Moon in December 1968. The crew's Christmas Eve broadcast and the Earthrise photograph were watched by a quarter of humanity.", type: "science" },
      { date: "Jul 20, 1969", title: "Apollo 11 — humans land on the Moon", summary: "Neil Armstrong and Buzz Aldrin walk on the lunar surface.", detail: "At 10:56 PM EDT on July 20, 1969, Neil Armstrong stepped onto the Moon. Over 600 million people watched on TV, fulfilling Kennedy's pledge and definitively winning the Space Race.", type: "science" },
    ]
  },
  "nelson mandela": {
    topic: "Nelson Mandela",
    intro: "Nelson Mandela's life embodies the triumph of human spirit over oppression, transforming from a militant freedom fighter to a global symbol of reconciliation and forgiveness. Imprisoned for 27 years for his anti-apartheid activism, Mandela emerged not seeking revenge but working to heal a divided nation, becoming South Africa's first Black president. His journey from prisoner to president demonstrates how one person's commitment to justice can reshape an entire country's destiny and inspire movements for equality worldwide.",
    outro: {
      summary: "Mandela's presidency dismantled apartheid's legal framework and established a multiracial democracy that became a model for post-conflict reconciliation. His Truth and Reconciliation Commission pioneered restorative justice approaches used globally. Surprisingly, Mandela learned Afrikaans in prison to better understand his guards, a skill that helped him negotiate with former enemies and contributed to South Africa's peaceful transition.",
      question: "How might global approaches to conflict resolution differ without Mandela's example of forgiveness..."
    },
    related: ["world war ii", "india independence", "arab spring"],
    events: [
      { date: "Jul 18, 1918", title: "Mandela born in Mvezo", summary: "Born into a Thembu royal family in South Africa's Eastern Cape.", detail: "Nelson Rolihlahla Mandela was born in Mvezo, a small village. His father was a local chief. A teacher gave him the English name 'Nelson.'", type: "culture" },
      { date: "1944", title: "Joins the ANC", summary: "Mandela co-founds the ANC Youth League.", detail: "Mandela joined the ANC and co-founded its Youth League with Oliver Tambo and Walter Sisulu, helping radicalize it from a moderate petition organization to one committed to mass action.", type: "political" },
      { date: "1960", title: "Sharpeville Massacre & ANC banned", summary: "Police kill 69 protesters; the ANC is outlawed.", detail: "Police shot 69 Black protesters in Sharpeville on March 21, 1960. The government banned the ANC. Mandela helped found the ANC's armed wing, Umkhonto we Sizwe.", type: "war" },
      { date: "1964", title: "Sentenced to life imprisonment", summary: "Mandela receives a life sentence at the Rivonia Trial.", detail: "Convicted of sabotage, Mandela declared: 'I am prepared to die' for a democratic society. He was sentenced to life and sent to Robben Island.", type: "political" },
      { date: "1964–90", title: "27 years in prison", summary: "Mandela endures imprisonment while becoming a global symbol of resistance.", detail: "Mandela spent 18 years on Robben Island before being moved to Pollsmoor Prison. He refused conditional release offers that required renouncing violence, growing into an international icon.", type: "political" },
      { date: "Feb 11, 1990", title: "Mandela walks free", summary: "After 27 years, Mandela is released from Victor Verster Prison.", detail: "Mandela walked out of prison on February 11, 1990, his fist raised, to a roaring global audience. He was 71 years old and had spent more than a quarter of his life behind bars.", type: "political" },
      { date: "1993", title: "Nobel Peace Prize awarded", summary: "Mandela and F.W. de Klerk jointly win the Nobel Peace Prize.", detail: "Mandela and President de Klerk were jointly awarded the Nobel Peace Prize for their negotiations to dismantle apartheid and establish a democratic, multiracial South Africa.", type: "political" },
      { date: "May 1994", title: "Elected South Africa's first Black president", summary: "Mandela takes office after South Africa's first fully democratic election.", detail: "The ANC won 62% of the vote in South Africa's first fully democratic election. At his inauguration, Mandela declared: 'Never again shall this beautiful land experience the oppression of one by another.'", type: "political" },
      { date: "Dec 5, 2013", title: "Mandela passes away aged 95", summary: "The world mourns the loss of one of history's greatest leaders.", detail: "Nelson Mandela died on December 5, 2013, at his home in Johannesburg. Over 100 heads of state attended his memorial, honoring a legacy of reconciliation and moral leadership.", type: "culture" },
    ]
  },
  "arab spring": {
    topic: "The Arab Spring",
    intro: "The Arab Spring erupted in 2010 as a wave of pro-democracy protests that swept across the Middle East and North Africa, challenging decades of authoritarian rule and inspiring hopes for democratic transformation. Sparked by a Tunisian street vendor's self-immolation, the movement spread through social media and public squares, toppling dictators in Tunisia, Egypt, Libya, and Yemen. What began as a unified call for dignity and freedom fractured into complex struggles that continue to reshape the region's political landscape.",
    outro: {
      summary: "The Arab Spring succeeded in Tunisia, establishing a fragile democracy, but led to prolonged conflicts in Syria, Libya, and Yemen that have cost millions of lives. The movement accelerated digital activism and social media's role in political change. Surprisingly, the protests also led to significant improvements in internet freedom in some countries, as governments temporarily lifted restrictions to avoid appearing repressive during the uprisings.",
      question: "What might the Middle East look like today if the Arab Spring had achieved its democratic goals across the region..."
    },
    related: ["nelson mandela", "india independence", "french revolution"],
    events: [
      { date: "Dec 2010", title: "Mohamed Bouazizi sets himself on fire", summary: "A Tunisian vendor's act of despair ignites a revolution.", detail: "When a police officer confiscated his vegetable cart, 26-year-old Bouazizi set himself on fire in protest. His act became the spark that ignited protests across Tunisia and the Arab world.", type: "culture" },
      { date: "Jan 14, 2011", title: "Ben Ali flees Tunisia", summary: "Tunisia's president flees after 23 years — the first domino falls.", detail: "Massive protests forced President Ben Ali to flee to Saudi Arabia on January 14, 2011. Tunisia became the first Arab country to successfully overthrow its government in the Jasmine Revolution.", type: "political" },
      { date: "Feb 11, 2011", title: "Mubarak resigns in Egypt", summary: "Egypt's president steps down after 30 years in power.", detail: "Hosni Mubarak resigned on February 11, 2011, handing power to the military after 18 days of Tahrir Square protests. Celebrations erupted across Egypt.", type: "political" },
      { date: "Feb 2011", title: "Libya erupts into civil war", summary: "Protests against Gaddafi turn violent, sparking civil war.", detail: "Protests in Libya quickly turned violent when Gaddafi's forces fired on demonstrators. NATO intervened under a UN mandate to protect civilians.", type: "war" },
      { date: "Mar 2011", title: "Syrian civil war begins", summary: "Peaceful protests crushed by Assad's forces spark a devastating war.", detail: "After protesters were shot by security forces, Syria descended into civil war. The conflict killed over 500,000 people and displaced half of Syria's population, drawing in global powers.", type: "war" },
      { date: "Oct 2011", title: "Gaddafi killed", summary: "Libyan leader Muammar Gaddafi is captured and killed by rebels.", detail: "Gaddafi was killed by rebel forces on October 20, 2011, after 42 years in power. His death ended the first Libyan civil war but left a power vacuum that led to a second.", type: "war" },
      { date: "2013", title: "Egypt's democracy reversed", summary: "Military coup ousts Egypt's first elected president.", detail: "President Mohamed Morsi was overthrown by the military in July 2013. General el-Sisi took power, installing a government more authoritarian than Mubarak's.", type: "political" },
      { date: "2010s–present", title: "Mixed legacy across the region", summary: "Tunisia briefly democratizes; most countries slide back to authoritarianism.", detail: "A decade on, results were deeply uneven. Tunisia achieved fragile democracy before backsliding. Syria, Libya, and Yemen were devastated by war. Egypt returned to authoritarian rule.", type: "political" },
    ]
  },
  "internet history": {
    topic: "History of the Internet",
    intro: "The internet's evolution from a military research project to the backbone of modern civilization represents one of humanity's most transformative technological achievements. Born from ARPANET in the 1960s, this global network of networks has revolutionized communication, commerce, and knowledge sharing, connecting billions of people in ways unimaginable to its creators. From dial-up modems to fiber optics, the internet's story is one of exponential growth and constant reinvention that continues to shape our world.",
    outro: {
      summary: "The internet has created unprecedented opportunities for education, entrepreneurship, and social connection, generating trillions in economic value and connecting billions of people. It has also given rise to social media, e-commerce, and remote work, fundamentally changing how we live and work. Surprisingly, the internet's original design included no security features, as its creators assumed it would be used only by trusted researchers—a decision that led to decades of cybersecurity challenges.",
      question: "How would human society function without the instant connectivity the internet provides..."
    },
    related: ["bitcoin", "elon musk", "ai history"],
    events: [
      { date: "1969", title: "ARPANET sends first message", summary: "The US military network sends its first transmission — the internet is born.", detail: "On October 29, 1969, a message was sent between UCLA and Stanford over ARPANET. The system crashed after two letters, but the age of networked computing had begun.", type: "science" },
      { date: "1983", title: "TCP/IP becomes the standard", summary: "The common language of the internet is established.", detail: "ARPANET adopted TCP/IP protocols on January 1, 1983 — the foundational communication rules that still govern how data travels across the internet today.", type: "science" },
      { date: "1991", title: "World Wide Web goes public", summary: "Tim Berners-Lee opens the Web to the world.", detail: "Tim Berners-Lee published the first website on August 6, 1991, making the World Wide Web publicly available. He invented HTML and HTTP while working at CERN in Switzerland.", type: "science" },
      { date: "1994", title: "Netscape Navigator launches", summary: "The first popular web browser puts the internet in everyone's hands.", detail: "Netscape Navigator made the web graphical and accessible to ordinary people, kickstarting the commercial internet era and triggering the dot-com boom.", type: "science" },
      { date: "1998", title: "Google founded", summary: "Larry Page and Sergey Brin build a better search engine.", detail: "Google was incorporated on September 4, 1998. Its PageRank algorithm delivered far better search results than competitors, and it would grow to dominate the web.", type: "economy" },
      { date: "2004", title: "Facebook launches", summary: "Mark Zuckerberg's social network begins at Harvard.", detail: "Facebook launched in February 2004, initially for Harvard students. It spread rapidly to other universities and then the world, fundamentally changing how people communicate and share information.", type: "culture" },
      { date: "2007", title: "iPhone and mobile internet explode", summary: "The smartphone transforms how people access the internet.", detail: "The iPhone's launch in 2007 triggered the mobile internet era. Within a few years, mobile devices surpassed desktops as the primary way people accessed the web worldwide.", type: "science" },
      { date: "2010s", title: "Social media dominates", summary: "Twitter, Instagram, and YouTube reshape media and politics.", detail: "Social media platforms became the dominant way billions consumed news, entertainment, and connected with others — with profound effects on culture, politics, and mental health.", type: "culture" },
      { date: "2022–present", title: "AI reshapes the internet", summary: "ChatGPT and large language models begin transforming the web.", detail: "The launch of ChatGPT in November 2022 triggered a wave of AI integration across the internet, beginning a new era of AI-generated content, search, and human-computer interaction.", type: "science" },
    ]
  },
  "india independence": {
    topic: "Indian Independence Movement",
    intro: "India's independence movement stands as one of history's greatest nonviolent struggles, mobilizing millions against British colonial rule through the visionary leadership of Mahatma Gandhi. From the salt march to the Quit India movement, this decades-long campaign combined civil disobedience, economic boycotts, and mass mobilization to challenge the world's largest empire. The movement not only won freedom for India but also inspired anti-colonial struggles worldwide and demonstrated the power of peaceful resistance.",
    outro: {
      summary: "India's independence established the world's largest democracy and inspired decolonization movements across Asia and Africa. The movement's emphasis on nonviolence influenced civil rights struggles from Martin Luther King to Nelson Mandela. Surprisingly, the British partition of India into India and Pakistan led to the largest migration in human history, with over 15 million people displaced and hundreds of thousands killed in communal violence.",
      question: "How might global politics differ if India had remained under British rule..."
    },
    related: ["nelson mandela", "french revolution", "arab spring"],
    events: [
      { date: "1857", title: "First War of Independence", summary: "Indian soldiers revolt against British East India Company rule.", detail: "The Sepoy Mutiny of 1857 was India's first large-scale armed uprising against British rule. Though suppressed, it led to the dissolution of the East India Company and direct British Crown rule over India.", type: "war" },
      { date: "1885", title: "Indian National Congress founded", summary: "India's first major political party is established.", detail: "The Indian National Congress was founded in December 1885, initially as a platform for educated Indians to express views to the British government. It would become the leading party of the independence movement.", type: "political" },
      { date: "1919", title: "Jallianwala Bagh Massacre", summary: "British troops kill hundreds of unarmed protesters in Amritsar.", detail: "On April 13, 1919, British General Dyer ordered troops to fire on a crowd of unarmed civilians in Amritsar, killing an estimated 379–1,000 people. The massacre turned millions against British rule.", type: "war" },
      { date: "1920", title: "Gandhi launches Non-Cooperation Movement", summary: "Gandhi calls for peaceful mass resistance against British rule.", detail: "Gandhi launched the Non-Cooperation Movement in 1920, urging Indians to boycott British goods, courts, and schools. It was the first nationwide mass movement against colonial rule.", type: "political" },
      { date: "1930", title: "Salt March", summary: "Gandhi leads a 240-mile march to protest the British salt tax.", detail: "Gandhi walked 240 miles to the sea at Dandi and made salt from seawater on April 6, 1930, defying British monopoly laws. The act inspired millions to civil disobedience and drew global attention.", type: "political" },
      { date: "1942", title: "Quit India Movement", summary: "Gandhi demands immediate British withdrawal from India.", detail: "Gandhi launched the Quit India Movement on August 8, 1942, demanding an end to British rule. The British arrested Gandhi and thousands of Congress leaders, but the movement showed colonial rule was unsustainable.", type: "political" },
      { date: "Aug 15, 1947", title: "India gains independence", summary: "India becomes free at midnight — Nehru's 'tryst with destiny' speech.", detail: "At midnight on August 15, 1947, India gained independence from Britain. Prime Minister Nehru addressed the nation: 'At the stroke of the midnight hour, India will awake to life and freedom.'", type: "political" },
      { date: "Jan 30, 1948", title: "Gandhi assassinated", summary: "The Father of the Nation is shot dead in New Delhi.", detail: "Mahatma Gandhi was shot by Hindu nationalist Nathuram Godse on January 30, 1948. Gandhi's assassination shocked the world and deprived India of its moral compass at a critical moment.", type: "political" },
      { date: "Jan 26, 1950", title: "India becomes a Republic", summary: "India adopts its constitution and becomes the world's largest democracy.", detail: "India's constitution came into force on January 26, 1950 — celebrated annually as Republic Day. The constitution enshrined democracy, secularism, and fundamental rights for all citizens.", type: "political" },
    ]
  },
  "apple": {
    topic: "Apple Inc.",
    intro: "Apple's transformation from a struggling computer company to the world's most valuable corporation represents a masterclass in innovation, design, and brand building. Founded by Steve Jobs and Steve Wozniak in a garage, Apple revolutionized personal computing with the Macintosh, then redefined music with the iPod, and completely reinvented mobile technology with the iPhone. Through iconic products and cultural impact, Apple has shaped how we interact with technology and perceive luxury in the digital age.",
    outro: {
      summary: "Apple's ecosystem of interconnected devices and services has created a loyal customer base worth hundreds of billions, while its design philosophy has influenced countless products across industries. The company's focus on user experience and privacy has set standards for the tech industry. Surprisingly, Apple's first product, the Apple I computer, was sold as a kit requiring users to add their own case, keyboard, and power supply—a far cry from today's polished consumer products.",
      question: "What would consumer technology look like without Apple's influence on design and user experience..."
    },
    related: ["iphone", "elon musk", "bitcoin"],
    events: [
      { date: "Apr 1976", title: "Apple founded in a garage", summary: "Steve Jobs, Wozniak, and Wayne start Apple in Los Altos.", detail: "Apple was founded on April 1, 1976, by Steve Jobs, Steve Wozniak, and Ronald Wayne. Wozniak had built the Apple I circuit board; Jobs saw the commercial potential and pushed to sell it.", type: "economy" },
      { date: "1984", title: "Macintosh launches with iconic ad", summary: "The Mac introduces the graphical user interface to the masses.", detail: "The Macintosh launched on January 24, 1984, introduced during the famous '1984' Super Bowl ad directed by Ridley Scott. It brought point-and-click computing to ordinary people.", type: "culture" },
      { date: "1985", title: "Jobs ousted from Apple", summary: "Steve Jobs is forced out of the company he founded.", detail: "After a power struggle with CEO John Sculley, Jobs was removed from his operational role and resigned in September 1985. He went on to found NeXT and acquire Pixar.", type: "economy" },
      { date: "1997", title: "Jobs returns to save Apple", summary: "Apple acquires NeXT, bringing Jobs back as Apple nears bankruptcy.", detail: "Apple was weeks from bankruptcy when it acquired NeXT for $429 million in December 1996, bringing Jobs back. He became CEO in 1997 and launched the 'Think Different' campaign.", type: "economy" },
      { date: "2001", title: "iPod and iTunes launch", summary: "Apple enters music with '1,000 songs in your pocket.'", detail: "The iPod launched in October 2001, followed by iTunes. The combination transformed the music industry, moving it from physical CDs to digital downloads and establishing Apple's consumer electronics dominance.", type: "culture" },
      { date: "2007", title: "iPhone changes everything", summary: "Apple reinvents the phone and creates the smartphone era.", detail: "The iPhone launched on June 29, 2007, combining phone, iPod, and internet in one device. It destroyed existing mobile incumbents and became Apple's most important and profitable product.", type: "science" },
      { date: "2010", title: "iPad creates the tablet market", summary: "Apple launches the iPad to widespread skepticism — it becomes a hit.", detail: "The iPad launched on April 3, 2010. Critics questioned who needed it. It sold 15 million units in its first year and created the modern tablet market.", type: "science" },
      { date: "Aug 2018", title: "Apple hits $1 trillion valuation", summary: "Apple becomes the first US company worth $1 trillion.", detail: "Apple crossed a $1 trillion market capitalization on August 2, 2018 — the first US publicly traded company to do so, a milestone reflecting the iPhone's extraordinary commercial success.", type: "economy" },
      { date: "2023", title: "Apple Vision Pro announced", summary: "Apple enters spatial computing with a $3,499 headset.", detail: "Apple unveiled the Vision Pro at WWDC 2023, a spatial computing headset blending AR and VR. It represented Apple's biggest product bet since the iPhone, launching in early 2024.", type: "science" },
    ]
  },
  "climate change": {
    topic: "Climate Change",
    intro: "Climate change represents humanity's greatest challenge, as rising temperatures and extreme weather threaten ecosystems, economies, and human civilization itself. Driven by industrial emissions of greenhouse gases, this global crisis demands unprecedented international cooperation and technological innovation to mitigate its worst effects. From melting glaciers to rising sea levels, climate change is already reshaping our world and forcing societies to confront the consequences of a century of fossil fuel dependence.",
    outro: {
      summary: "Climate change has spurred a global transition to renewable energy, with solar and wind power becoming cheaper than fossil fuels in many regions. International agreements like the Paris Accord have committed nations to emissions reductions, while technological innovations offer hope for carbon capture and geoengineering. Surprisingly, the crisis has also accelerated scientific collaboration, with researchers from rival nations working together on climate models and solutions despite geopolitical tensions.",
      question: "How would human civilization adapt if global temperatures rose 2 degrees Celsius above pre-industrial levels..."
    },
    related: ["world war ii", "covid-19", "elon musk"],
    events: [
      { date: "1824", title: "Greenhouse effect discovered", summary: "Joseph Fourier identifies that Earth's atmosphere traps heat.", detail: "French mathematician Joseph Fourier described what we now call the greenhouse effect — the atmosphere trapping solar heat like glass in a greenhouse. It was the first scientific description of Earth's heat regulation.", type: "science" },
      { date: "1958", title: "Keeling Curve begins", summary: "Charles Keeling starts measuring CO₂ at Mauna Loa — still ongoing.", detail: "Charles Keeling began systematic CO₂ measurements at Hawaii's Mauna Loa Observatory in 1958. The resulting Keeling Curve is the longest record of atmospheric CO₂ and the clearest evidence of rising emissions.", type: "science" },
      { date: "1988", title: "NASA's James Hansen warns Congress", summary: "A scientist tells the US Senate global warming is already happening.", detail: "NASA scientist James Hansen testified before the US Senate in June 1988, stating with '99% confidence' that the Earth was warming due to human activities — the first major political moment for climate change.", type: "political" },
      { date: "1992", title: "Earth Summit in Rio", summary: "World leaders gather to address the climate crisis for the first time.", detail: "The UN Conference on Environment and Development in Rio de Janeiro produced the UN Framework Convention on Climate Change, the first global treaty aimed at stabilizing greenhouse gas concentrations.", type: "political" },
      { date: "1997", title: "Kyoto Protocol signed", summary: "Industrialized nations commit to cutting emissions for the first time.", detail: "The Kyoto Protocol was adopted in December 1997, requiring industrialized nations to cut greenhouse gas emissions. The US signed but Congress never ratified it, limiting its impact.", type: "political" },
      { date: "2006", title: "An Inconvenient Truth released", summary: "Al Gore's documentary brings climate change to mainstream audiences.", detail: "Al Gore's documentary reached millions worldwide, winning an Oscar and the Nobel Peace Prize for Gore. It marked a turning point in public awareness of climate change.", type: "culture" },
      { date: "2015", title: "Paris Agreement signed", summary: "195 nations agree to limit warming to 1.5–2°C above pre-industrial levels.", detail: "The Paris Agreement was adopted on December 12, 2015 — the most ambitious global climate accord ever. Countries committed to nationally determined emissions reduction targets.", type: "political" },
      { date: "2018", title: "Greta Thunberg begins school strike", summary: "A 15-year-old Swedish girl sparks a global youth climate movement.", detail: "Greta Thunberg began striking outside the Swedish parliament on August 20, 2018. Her Fridays for Future movement spread to millions of young people across 150 countries within a year.", type: "culture" },
      { date: "2021", title: "COP26 in Glasgow", summary: "World leaders make new pledges to phase out coal and cut methane.", detail: "COP26 in Glasgow produced commitments to phase down coal, cut methane emissions, and end deforestation. Scientists warned the pledges were still insufficient to limit warming to 1.5°C.", type: "political" },
    ]
  },
  "world wide web": {
    topic: "World Wide Web",
    intro: "The World Wide Web transformed the internet from a niche tool for scientists and academics into the ubiquitous platform that powers modern life, enabling instant global communication and commerce. Invented by Tim Berners-Lee at CERN in 1989, the web's simple system of hyperlinks and universal protocols made the internet accessible to ordinary people, sparking an information revolution. From static web pages to interactive social platforms, the web has evolved rapidly while maintaining its foundational principles of openness and connectivity.",
    outro: {
      summary: "The web has created unprecedented opportunities for education, entrepreneurship, and social connection, generating trillions in economic value and connecting billions of people. It has also given rise to new forms of media, commerce, and community that transcend geographical boundaries. Surprisingly, the web's inventor, Tim Berners-Lee, made it deliberately open and free, rejecting opportunities to patent or monetize his creation to ensure it remained a public good.",
      question: "What would daily life be like without the instant access to information that the web provides..."
    },
    related: ["internet history", "bitcoin", "elon musk"],
    events: [
      { date: "Mar 1989", title: "Berners-Lee proposes the Web", summary: "A CERN scientist proposes a global information system.", detail: "Tim Berners-Lee submitted a proposal titled 'Information Management: A Proposal' to his boss at CERN in March 1989. His boss wrote 'vague but exciting' on the cover — and approved it.", type: "science" },
      { date: "Aug 1991", title: "First website goes live", summary: "The world's first website launches at CERN.", detail: "Tim Berners-Lee published the world's first website on August 6, 1991, describing the World Wide Web project itself. It was hosted on his NeXT computer at CERN.", type: "science" },
      { date: "1993", title: "Mosaic browser launches", summary: "The first graphical browser makes the web visual and accessible.", detail: "The Mosaic browser, developed at the University of Illinois, was the first to display images inline with text. It made the web accessible to non-technical users and triggered an explosion of growth.", type: "science" },
      { date: "1994", title: "Amazon and Yahoo founded", summary: "The first great web companies are born.", detail: "Amazon launched in July 1994 as an online bookstore, and Yahoo was founded the same year as a web directory. Both would become internet giants and define the early commercial web.", type: "economy" },
      { date: "1998", title: "Google launches", summary: "PageRank delivers dramatically better search results.", detail: "Google launched in September 1998 with a search algorithm that ranked pages by the number and quality of links pointing to them, delivering far better results than existing search engines.", type: "science" },
      { date: "2000", title: "Dot-com bubble bursts", summary: "Trillions of dollars in web company value evaporate overnight.", detail: "After years of irrational investment in internet companies, the NASDAQ peaked in March 2000 and then crashed 78% over two years. Hundreds of dot-com companies went bankrupt.", type: "economy" },
      { date: "2004", title: "Web 2.0 era — social and user-generated content", summary: "Facebook, Wikipedia, and YouTube transform the web from read to read-write.", detail: "The mid-2000s saw the rise of user-generated content platforms. Ordinary people could now create and publish content, not just consume it — fundamentally changing the web's nature.", type: "culture" },
      { date: "2010s", title: "Mobile web overtakes desktop", summary: "Smartphones become the primary way people access the internet.", detail: "By the mid-2010s, more than half of all web traffic came from mobile devices. Websites redesigned for mobile-first experiences as the smartphone replaced the PC as the primary internet gateway.", type: "science" },
    ]
  },
  "elon musk": {
    topic: "Elon Musk",
    intro: "Elon Musk's relentless pursuit of ambitious goals has made him one of the most influential figures in modern technology and space exploration, challenging conventional wisdom about what's possible. From electric vehicles to reusable rockets to neural interfaces, Musk's companies—Tesla, SpaceX, Neuralink, and The Boring Company—push the boundaries of engineering and sustainability. His vision of a multiplanetary humanity and sustainable energy future continues to inspire and polarize in equal measure.",
    outro: {
      summary: "Musk's companies have revolutionized electric vehicles, space travel, and renewable energy, making sustainable technologies accessible and accelerating the transition away from fossil fuels. His work has inspired a generation of engineers and entrepreneurs to tackle ambitious problems. Surprisingly, Musk taught himself rocket science by reading textbooks, demonstrating how autodidactic learning and determination can overcome traditional educational barriers.",
      question: "How might technological innovation differ without visionary entrepreneurs like Elon Musk..."
    },
    related: ["space race", "apple", "climate change"],
    events: [
      { date: "1995", title: "Zip2 founded — first company", summary: "Musk drops out of Stanford after two days to start his first startup.", detail: "Musk enrolled in a Stanford PhD program in 1995 but left after two days to start Zip2 with his brother Kimbal — an online city guide for newspapers. Compaq acquired it in 1999 for $307 million.", type: "economy" },
      { date: "1999", title: "X.com founded — becomes PayPal", summary: "Musk founds an online payments company that becomes PayPal.", detail: "Musk co-founded X.com in 1999, an online financial services company. It merged with Confinity to become PayPal, which eBay acquired in 2002 for $1.5 billion — Musk's share was $180 million.", type: "economy" },
      { date: "2002", title: "SpaceX founded", summary: "Musk starts a rocket company to make humanity multiplanetary.", detail: "Musk founded SpaceX in May 2002 with $100 million of his own money. His goal: reduce space transportation costs and ultimately colonize Mars. Most people in the industry thought he would fail.", type: "science" },
      { date: "2004", title: "Joins Tesla as chairman", summary: "Musk invests in Tesla and becomes its driving force.", detail: "Musk led Tesla's Series A funding in 2004 and joined its board as chairman. He later became CEO in 2008. Though he didn't found Tesla, he is credited with transforming it into the world's most valuable automaker.", type: "economy" },
      { date: "2008", title: "SpaceX's Falcon 1 reaches orbit", summary: "After three failures, SpaceX becomes the first private company to reach orbit.", detail: "Falcon 1's fourth launch successfully reached orbit on September 28, 2008 — the first privately developed liquid-fueled rocket to do so. SpaceX was nearly bankrupt; this success saved the company.", type: "science" },
      { date: "2015", title: "Falcon 9 lands its first booster", summary: "SpaceX successfully lands a rocket booster — reusability becomes real.", detail: "SpaceX landed an orbital-class Falcon 9 booster vertically on December 21, 2015, proving reusable rockets were possible. This breakthrough slashed launch costs and revolutionized the space industry.", type: "science" },
      { date: "2021", title: "Becomes world's richest person", summary: "Musk briefly surpasses Bezos as the world's wealthiest individual.", detail: "Musk overtook Jeff Bezos as the world's wealthiest person in January 2021, driven by surging Tesla stock. His net worth briefly exceeded $300 billion — an unprecedented fortune.", type: "economy" },
      { date: "Oct 2022", title: "Acquires Twitter for $44 billion", summary: "Musk completes his controversial purchase of Twitter, renaming it X.", detail: "After months of legal battles, Musk completed his $44 billion acquisition of Twitter in October 2022. He fired most of the staff, changed the company's name to X, and made sweeping changes to content moderation.", type: "economy" },
    ]
  },
  "world war i": {
    topic: "World War I",
    intro: "World War I shattered the optimism of the early 20th century, plunging Europe into four years of industrialized slaughter that killed millions and redrew the map of the world. Triggered by the assassination of Archduke Franz Ferdinand, the war began as a European conflict but drew in colonies and nations worldwide, introducing trench warfare, chemical weapons, and aerial combat. The war's devastation led to the collapse of empires and the rise of new ideologies that would shape the turbulent 20th century.",
    outro: {
      summary: "World War I's aftermath created the modern Middle East through the Sykes-Picot Agreement and led to the Russian Revolution, fundamentally reshaping global politics. The war accelerated technological innovation in aviation, medicine, and communication. Surprisingly, the conflict also led to women's suffrage movements gaining momentum, as women took on traditionally male roles in factories and demonstrated their capability for political participation.",
      question: "What might the 20th century have looked like if World War I had been prevented..."
    },
    related: ["world war ii", "french revolution", "cold war"],
    events: [
      { date: "Jun 28, 1914", title: "Archduke Franz Ferdinand assassinated", summary: "The spark that ignited the Great War — shot in Sarajevo.", detail: "Archduke Franz Ferdinand, heir to the Austro-Hungarian throne, was assassinated in Sarajevo by Gavrilo Princip, a Bosnian Serb nationalist. The act triggered a cascade of alliances that plunged Europe into war.", type: "political" },
      { date: "Aug 1914", title: "War declared — Europe mobilizes", summary: "Austria-Hungary, Germany, Russia, France, and Britain all declare war within weeks.", detail: "The assassination triggered alliance obligations. Austria-Hungary declared war on Serbia. Russia mobilized. Germany declared war on Russia and France. Britain declared war on Germany after it invaded Belgium.", type: "war" },
      { date: "1915", title: "Gallipoli Campaign", summary: "Allied forces attempt to knock Ottoman Empire out of the war — and fail.", detail: "The Gallipoli campaign was a disastrous Allied attempt to seize the Dardanelles and knock Turkey out of the war. It cost over 250,000 Allied casualties and ended in evacuation, becoming a defining national trauma for Australia and New Zealand.", type: "war" },
      { date: "1916", title: "Battle of the Somme", summary: "Britain suffers 57,000 casualties on the first day of the bloodiest battle.", detail: "The Battle of the Somme (July–November 1916) became one of history's bloodiest, with over 1 million total casualties. On the first day alone, Britain suffered 57,470 casualties — the worst day in British military history.", type: "war" },
      { date: "1917", title: "US enters the war", summary: "America joins the Allies after German submarine attacks on US ships.", detail: "The US declared war on Germany on April 6, 1917, following German submarine warfare targeting US ships and the interception of the Zimmermann Telegram, in which Germany asked Mexico to attack the US.", type: "political" },
      { date: "Nov 11, 1918", title: "Armistice signed — war ends", summary: "Fighting ceases at 11am on the 11th day of the 11th month.", detail: "Germany signed the Armistice on November 11, 1918, ending four years of fighting that killed over 20 million people. The war reshaped the map of Europe and set the conditions for World War II.", type: "war" },
      { date: "Jun 1919", title: "Treaty of Versailles signed", summary: "Germany accepts harsh terms, sowing seeds of future conflict.", detail: "The Treaty of Versailles imposed massive reparations and territorial losses on Germany, assigning sole blame for the war. The harsh terms created deep resentment that Hitler would exploit two decades later.", type: "political" },
    ]
  },
  "ai history": {
    topic: "History of Artificial Intelligence",
    intro: "The history of artificial intelligence represents humanity's quest to understand and replicate intelligence, evolving from theoretical concepts to transformative technologies that are reshaping every aspect of modern life. From Alan Turing's philosophical questions to today's large language models, AI has progressed through cycles of hype and disappointment, each breakthrough building on the last. As AI becomes increasingly capable, it raises profound questions about work, creativity, and the nature of human intelligence itself.",
    outro: {
      summary: "AI has revolutionized fields from medical diagnosis to autonomous vehicles, creating new industries and solving previously intractable problems. The technology has also raised important ethical questions about bias, privacy, and the future of work. Surprisingly, many early AI researchers believed human-level AI was only decades away, but progress was slower than expected due to the complexity of tasks humans perform effortlessly, like visual recognition.",
      question: "How would society adapt if artificial intelligence achieved human-level general intelligence..."
    },
    related: ["elon musk", "bitcoin", "internet history"],
    events: [
      { date: "1950", title: "Turing proposes the Imitation Game", summary: "Alan Turing asks: 'Can machines think?'", detail: "In his landmark paper 'Computing Machinery and Intelligence,' Alan Turing proposed the Imitation Game (now the Turing Test) as a measure of machine intelligence — founding the philosophical basis of AI.", type: "science" },
      { date: "1956", title: "Dartmouth Conference coins 'AI'", summary: "The field of Artificial Intelligence is officially born.", detail: "John McCarthy, Marvin Minsky, and others gathered at Dartmouth College in the summer of 1956. McCarthy coined the term 'artificial intelligence,' marking the formal birth of AI as an academic discipline.", type: "science" },
      { date: "1997", title: "Deep Blue defeats Kasparov", summary: "IBM's chess computer beats the world champion for the first time.", detail: "IBM's Deep Blue defeated world chess champion Garry Kasparov in a six-game match in May 1997, the first time a computer defeated a reigning world champion under tournament conditions.", type: "science" },
      { date: "2011", title: "IBM Watson wins Jeopardy!", summary: "IBM's AI defeats Jeopardy! champions, showcasing natural language processing.", detail: "IBM's Watson defeated Jeopardy! champions Ken Jennings and Brad Rutter in February 2011, demonstrating that computers could understand natural language questions well enough to beat the best human players.", type: "science" },
      { date: "2012", title: "AlexNet transforms deep learning", summary: "A neural network crushes the ImageNet competition — the deep learning era begins.", detail: "Geoffrey Hinton's AlexNet won the ImageNet image recognition competition by a huge margin in 2012, demonstrating the power of deep neural networks. This single result triggered the modern deep learning revolution.", type: "science" },
      { date: "2016", title: "AlphaGo defeats world Go champion", summary: "DeepMind's AI wins at the most complex board game — a decade ahead of predictions.", detail: "DeepMind's AlphaGo defeated Lee Sedol 4-1 in March 2016, shocking experts who thought human-level Go play was at least a decade away. It demonstrated AI's ability to master complex intuitive tasks.", type: "science" },
      { date: "2017", title: "Transformer architecture published", summary: "'Attention is All You Need' — the paper that powers modern AI.", detail: "Google researchers published the Transformer architecture in 2017. It replaced recurrent networks for language tasks and became the foundation for BERT, GPT, and virtually every major AI language model that followed.", type: "science" },
      { date: "Nov 2022", title: "ChatGPT launches", summary: "OpenAI's chatbot reaches 100 million users in two months.", detail: "OpenAI launched ChatGPT on November 30, 2022. It reached 100 million users in just two months — the fastest-growing consumer application in history — triggering a global race to develop and deploy AI.", type: "science" },
      { date: "2023–present", title: "The AI race accelerates", summary: "Google, Microsoft, Anthropic, and Meta compete in the AI arms race.", detail: "2023 saw the release of GPT-4, Claude, Gemini, Llama, and dozens of other models. Generative AI began transforming industries from software to medicine, sparking global debates about regulation, safety, and jobs.", type: "science" },
    ]
  },
  "amazon": {
    topic: "Amazon",
    intro: "Amazon's evolution from an online bookstore to the world's most influential retailer and cloud computing giant demonstrates the power of customer obsession and long-term thinking in business. Founded by Jeff Bezos in 1994, the company began with books but quickly expanded into everything, using data and technology to anticipate customer needs before they were expressed. Amazon's relentless innovation has not only transformed retail but also created entirely new industries and business models.",
    outro: {
      summary: "Amazon has become the backbone of global e-commerce, controlling significant market share in retail, cloud computing, and digital advertising. Its logistics innovations have set new standards for speed and efficiency in delivery. Surprisingly, Amazon's original business plan included selling anything that could be sold online, but Bezos initially focused on books because they offered the widest selection and easiest shipping— a strategic choice that proved crucial to early success.",
      question: "How would consumer shopping and business operations change without companies like Amazon..."
    },
    related: ["bitcoin", "apple", "world wide web"],
    events: [
      { date: "Jul 1994", title: "Amazon founded as an online bookstore", summary: "Jeff Bezos starts Amazon in his Bellevue garage.", detail: "Jeff Bezos founded Amazon on July 5, 1994, initially as an online bookstore. He chose books because they had a simple, universal format and nearly infinite variety — perfect for the early web.", type: "economy" },
      { date: "1997", title: "Amazon goes public at $18/share", summary: "Amazon IPOs — most analysts call it a money-losing folly.", detail: "Amazon went public on May 15, 1997 at $18 per share. Many analysts were skeptical of its prospects, nicknaming it 'Amazon.bomb.' Bezos's long-term thinking and willingness to lose money confounded critics for years.", type: "economy" },
      { date: "2005", title: "Amazon Prime launches", summary: "Free two-day shipping for $79/year changes retail forever.", detail: "Amazon Prime launched in February 2005, offering unlimited free two-day shipping for $79 annually. It created a loyalty ecosystem that locked in customers and dramatically increased purchase frequency.", type: "economy" },
      { date: "2006", title: "AWS launches — cloud computing begins", summary: "Amazon launches cloud infrastructure — its most profitable business.", detail: "Amazon Web Services launched publicly in 2006, offering computing and storage as on-demand services. AWS became the backbone of the modern internet and Amazon's most profitable division.", type: "science" },
      { date: "2007", title: "Kindle launches", summary: "Amazon's e-reader transforms book publishing.", detail: "The Kindle launched in November 2007 and sold out in 5.5 hours. It transformed how people read books and gave Amazon control over digital book distribution, disrupting traditional publishers.", type: "culture" },
      { date: "2014", title: "Alexa and Echo introduced", summary: "Amazon creates the smart speaker and voice assistant market.", detail: "Amazon launched the Echo speaker and Alexa voice assistant in November 2014, creating an entirely new product category. Alexa grew into a platform with tens of thousands of third-party skills.", type: "science" },
      { date: "2018", title: "Amazon hits $1 trillion valuation", summary: "Amazon joins Apple as only the second US company worth $1 trillion.", detail: "Amazon briefly crossed a $1 trillion market cap in September 2018, reflecting the enormous scale of its retail, cloud, and advertising businesses.", type: "economy" },
      { date: "2021", title: "Bezos steps down as CEO", summary: "Andy Jassy takes over as Bezos becomes executive chairman.", detail: "Jeff Bezos stepped down as Amazon's CEO on July 5, 2021 — the company's 27th anniversary — handing the role to AWS chief Andy Jassy. Bezos launched to space on Blue Origin the same month.", type: "economy" },
    ]
  },
  "covid 19": {
    topic: "COVID-19 Pandemic",
    intro: "The COVID-19 pandemic exposed the fragility of global interconnectedness, forcing humanity to confront a microscopic threat that shut down economies, isolated populations, and claimed millions of lives. Emerging from Wuhan, China in late 2019, the virus spread with unprecedented speed, overwhelming healthcare systems and challenging governments worldwide. The crisis accelerated digital transformation, vaccine development, and remote work, while highlighting inequalities in healthcare and economic resilience.",
    outro: {
      summary: "The pandemic accelerated the adoption of remote work, e-commerce, and telemedicine, permanently changing how many people work and access healthcare. It also spurred unprecedented scientific collaboration, resulting in vaccines developed in record time. Surprisingly, the crisis led to significant environmental improvements, including reduced carbon emissions and cleaner air in major cities as economic activity slowed.",
      question: "What permanent changes to society might result from the COVID-19 pandemic..."
    },
    related: ["climate change", "world war ii", "ai history"],
    events: [
      { date: "Dec 2019", title: "Mysterious pneumonia cases in Wuhan", summary: "China reports unusual pneumonia clusters to the WHO.", detail: "In December 2019, Chinese authorities reported a cluster of pneumonia cases of unknown cause in Wuhan, Hubei province. The pathogen was later identified as a novel coronavirus, SARS-CoV-2.", type: "science" },
      { date: "Jan 2020", title: "WHO declares public health emergency", summary: "The WHO issues its highest alert as the virus spreads internationally.", detail: "The WHO declared a Public Health Emergency of International Concern on January 30, 2020. By then, the virus had spread to more than 18 countries outside China.", type: "political" },
      { date: "Mar 11, 2020", title: "WHO declares pandemic", summary: "COVID-19 is officially declared a global pandemic.", detail: "The WHO declared COVID-19 a pandemic on March 11, 2020, as cases surged across Europe and the Americas. Within days, governments worldwide locked down their populations in unprecedented peacetime measures.", type: "political" },
      { date: "Mar 2020", title: "Global lockdowns begin", summary: "Billions of people confined to their homes to slow the virus.", detail: "By late March 2020, over a billion people were under lockdown orders. Schools closed, businesses shuttered, and streets emptied worldwide. The global economy suffered its sharpest peacetime contraction.", type: "political" },
      { date: "Nov 2020", title: "Vaccines show 90%+ efficacy", summary: "Pfizer and Moderna announce breakthrough vaccine trial results.", detail: "Pfizer-BioNTech announced 90%+ vaccine efficacy on November 9, 2020, followed by Moderna days later. The results — delivered in under a year — represented the fastest vaccine development in history.", type: "science" },
      { date: "Dec 2020", title: "Mass vaccination begins", summary: "UK and US begin the largest vaccination campaigns in history.", detail: "The UK began mass COVID-19 vaccination on December 8, 2020, followed by the US on December 14. The campaigns used novel mRNA technology and scaled to hundreds of millions of doses within months.", type: "science" },
      { date: "Late 2021", title: "Delta and Omicron variants emerge", summary: "New variants spread faster, challenging vaccine immunity.", detail: "The Delta variant surged in mid-2021, and Omicron emerged in November 2021 and spread globally at unprecedented speed. Omicron proved more transmissible but generally less severe, accelerating the pandemic's transition to endemic.", type: "science" },
      { date: "May 2023", title: "WHO ends global health emergency", summary: "After more than three years, COVID-19 is no longer a global emergency.", detail: "The WHO declared the end of COVID-19 as a public health emergency of international concern on May 5, 2023. The pandemic had killed an estimated 7 million officially and over 20 million by excess mortality estimates.", type: "political" },
    ]
  },
};

export const PRESET_TOPICS = [
  "World War II", "Cold War", "Bitcoin", "iPhone",
  "French Revolution", "Space Race", "Nelson Mandela", "Arab Spring",
  "Internet History", "India Independence", "Apple", "Climate Change",
  "World War I", "AI History", "Amazon", "COVID-19",
];

export function findTimeline(query) {
  const key = query.toLowerCase().replace(/[^a-z0-9 ]/g, "").trim();
  const directMatch = Object.keys(TOPICS).find(k => key === k);
  if (directMatch) return TOPICS[directMatch];
  const partialMatch = Object.keys(TOPICS).find(k => key.includes(k) || k.includes(key));
  if (partialMatch) return TOPICS[partialMatch];
  return null;
}

export function searchTopics(query) {
  if (!query || query.trim().length < 2) return []
  const q = query.toLowerCase().trim()
  return Object.values(TOPICS)
    .filter(t =>
      t.topic.toLowerCase().includes(q) ||
      q.split(' ').some(word =>
        t.topic.toLowerCase().includes(word)
      )
    )
    .slice(0, 6)
    .map(t => ({
      key: t.topic.toLowerCase()
        .replace(/[^a-z0-9]+/g, '-'),
      label: t.topic,
      eventCount: t.events.length
    }))
}
